version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: herbtrace
      POSTGRES_USER: herbtrace
      POSTGRES_PASSWORD: herbtrace123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://herbtrace:herbtrace123@db:5432/herbtrace
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A herbtrace worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://herbtrace:herbtrace123@db:5432/herbtrace
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
